# Build stage
FROM node:22-alpine as build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build -- frontend --configuration production

# Production stage
FROM nginx:alpine
# Copier le build Angular
COPY --from=build /app/dist/frontend /usr/share/nginx/html
# Copier la config Nginx depuis le projet
COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
